name: Mirror to Codeberg
on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * 0'
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Mirror repository
        env:
          CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        run: |
          git -c http.extraHeader="Authorization: basic $(echo -n "gl0bal01:${CODEBERG_TOKEN}" | base64)" push --all --force https://codeberg.org/gl0bal01/discord-osint-assistant.git
          git -c http.extraHeader="Authorization: basic $(echo -n "gl0bal01:${CODEBERG_TOKEN}" | base64)" push --tags --force https://codeberg.org/gl0bal01/discord-osint-assistant.git
